### ISSUE TITLE
Setting keys from environment variables

### ISSUE THREAD

**Issue by SebastianOsinski** [FutureWorkshops/bitrise-step-cocoapod-key#2]
Hi. Thanks for providing great step! I have a question regarding setting keys. According to `cocoapods-keys` [documentation](https://github.com/orta/cocoapods-keys#continuous-integration) it's possible to pass key values from environment variables (Cocoapods-keys looks for env vars first then in Keychain). I'm wondering why isn't this step using that feature and instead requires to pass keys and values in config?

**Comment by igorcferreira** [comment]
@SebastianOsinski This step matches the development stack that each dev has in the company machines (and auxiliary scripts). So, it was the first "easy" approach. Thanks for the link/recommendation. I'll take a look and see how/if I can improve it 😄

**Comment by igorcferreira** [comment]
@SebastianOsinski I read further on this, and saw that the strategy to use env var instead of keychain passed value is something that bypass this step. So, it would be a way to use the tool that makes this code "useless". Given that: I'll close this issue. Going a bit more in-depth of the why our company decided to go with this approach:

The naming of the keys, on iOS code do not need to follow the same convention as the CI environment flags declarations. Even, changing from project A, and project B. This step does the middle ground of aligning the two worlds. Also, after some tests, we saw that this makes a bit easy to configure multiple types of build types (staging, qa, prod, etc), once that the env vars did not need to be necessarily overwritten, just used a new env in a new sub workflow (specially true for PR workflows where the Secrets are not exposed).
